waypoints:
  - name: "Goal_1"
    position:
      x: -4.0
      y: -4.0
      z: 0.0
    orientation:
      x: 0.0
      y: 0.0
      z: 0.0
      w: 1.0    

  - name: "Goal_2"
    position:
      x: -9.0
      y: -1.5
      z: 0.0
    orientation:
      x: 0.0
      y: 0.0
      z: 0.0
      w: 1.0

  - name: "Goal_3"
    position:
      x: -9.0
      y: 3.5
      z: 0.0
    orientation:
      x: 0.0
      y: 0.0
      z: 0.0
      w: 1.0

  - name: "Goal_4"
    position:
      x: -5.0
      y: 3.5
      z: 0.0
    orientation:
      x: 0.0
      y: 0.0
      z: 0.0
      w: 1.0 
  
  - name: "Goal_5"
    position:
      x: 0.0
      y: 3.5
      z: 0.0
    orientation:
      x: 0.0
      y: 0.0
      z: 0.0
      w: 1.0 

  - name: "Goal_6"
    position:
      x: 6.1
      y: 4.6
      z: 0.0
    orientation:
      x: 0.0
      y: 0.0
      z: 0.0
      w: 1.0

  - name: "Goal_7"
    position:
      x: 6.2
      y: 0.15
      z: 0.0
    orientation:
      x: 0.0
      y: 0.0
      z: 0.0
      w: 1.0

  - name: "Goal_8"
    position:
      x: 9.2
      y: 0.15
      z: 0.0
    orientation:
      x: 0.0
      y: 0.0
      z: 0.0
      w: 1.0

  - name: "Goal_9"
    position:
      x: 3.9
      y: 0.15
      z: 0.0
    orientation:
      x: 0.0
      y: 0.0
      z: 0.0
      w: 1.0    

  - name: "Goal_10"
    position:
      x: 1.0
      y: 0.15
      z: 0.0
    orientation:
      x: 0.0
      y: 0.0
      z: 0.0
      w: 1.0 

  - name: "Goal_11"
    position:
      x: 2.0
      y: -4.6
      z: 0.0
    orientation:
      x: 0.0
      y: 0.0
      z: 0.0
      w: 1.0