waypoints:
  - name: "Goal_1"
    position:
      x: 0.5
      y: 3.0
      z: 0.0
    orientation:  # Y = 0 degrees
      x: 0.0
      y: 0.0
      z: -0.7071
      w: 0.7071 

  - name: "Goal_2"
    position:
      x: 0.5
      y: 9.0
      z: 0.0
    orientation:  # Y = 30 degrees in radians
      x: 0.0
      y: 0.0
      z: -0.5
      w: 0.866  

  - name: "Goal_3"
    position:
      x: 4.9
      y: 9.9
      z: 0.0
    orientation:  # Y = 180 degrees in radians
      x: 0.0
      y: 0.0
      z: 0.0
      w: -1.0 

  - name: "Goal_4"
    position:
      x: 1.0
      y: 5.2
      z: 0.0
    orientation:  # Y = 75 degrees in radians
      x: 0.0
      y: 0.0
      z: -0.9239
      w: 0.3827 